[package]
name = "opencc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "=0.8.9"
regex = "1.12.3"
lazy_static = "1.5.0"